name: nutrabit_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.7
  file_picker: ^10.1.2
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_data_connect: ^0.1.4+1
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.2.0
  flutter_svg: ^1.1.6
  go_router: ^15.1.1
  html: ^0.15.6
  path: ^1.8.0
  table_calendar: ^3.1.3
  universal_io: ^2.2.2
  uuid: ^4.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  fake_cloud_firestore: ^3.1.0
  mockito: ^5.4.2
  mocktail: ^1.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/img/
